var divElement = document.getElementById('viz1569220068530');                    
var vizElement = divElement.getElementsByTagName('object')[0];                    
vizElement.style.minWidth='420px';
// vizElement.style.maxWidth='100%';
vizElement.style.minHeight='587px';
vizElement.style.width='100%';
vizElement.style.maxHeight=(divElement.offsetWidth*0.75)+'px';         
var scriptElement = document.createElement('script');                    
scriptElement.src = 'https://public.tableau.com/javascripts/api/viz_v1.js';                    
vizElement.parentNode.insertBefore(scriptElement, vizElement);